# Generated by Django 4.2.7 on 2024-04-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_totalreviewcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imageUrl',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='brandName',
            field=models.CharField(default='YourDefaultValueHere', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Bidon', 'Bidon'), ('Balai', 'Balai'), ('Raclette', 'Raclette'), ('Chiffon', 'Chiffon'), ('textile', 'Textile')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='', max_digits=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='totalReviewCount',
            field=models.IntegerField(),
        ),
    ]
