# Generated by Django 4.2.7 on 2024-05-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brandName',
            field=models.CharField(choices=[('Prima', 'prima'), ('Cleantex', 'cleantex'), ('Parex', 'parex'), ('Ariane', 'ariane'), ('Brilex', 'brilex'), ('Aigle', 'aigle'), ('Bingo', 'bingo'), ('Ariel', 'ariel'), ('AMIR', 'amir'), ('Wingo', 'wingo'), ('Bref', 'bref'), ('Deter clean', 'deter clean'), ('Dorex', 'dorex'), ('Vavo', 'vavo'), ('Le Chat', 'le_chat')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Bidon', 'Bidon'), ('Balai', 'Balai'), ('Raclette', 'Raclette'), ('Chiffon', 'Chiffon'), ('textile', 'Textile'), ('liquide', 'Liquide')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='00', max_digits=7),
        ),
    ]
