# Generated by Django 5.0.4 on 2024-05-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Bidon', 'Bidon'), ('Balai', 'Balai'), ('Raclette', 'Raclette'), ('Chiffon', 'Chiffon'), ('textile', 'Textile'), ('liquide', 'Liquide'), ('brosse', 'Brosse')], max_length=50),
        ),
    ]
