# Generated by Django 5.0.4 on 2024-05-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Bidon', 'Bidon'), ('Balai', 'Balai'), ('Raclette', 'Raclette'), ('Chiffon', 'Chiffon'), ('textile', 'Textile'), ('liquide', 'Liquide'), ('brosse', 'Brosse'), ('manche', 'Manche'), ('pelle', 'Pelle'), ('mop', 'Mop')], max_length=50),
        ),
    ]
