# Generated by Django 5.0.4 on 2024-05-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brandName',
            field=models.CharField(choices=[('Prima', 'prima'), ('Cleantex', 'cleantex'), ('Parex', 'parex'), ('Ariane', 'ariane'), ('Brilex', 'brilex'), ('Aigle', 'aigle'), ('Bingo', 'bingo'), ('Ariel', 'ariel'), ('AMIR', 'amir'), ('Le Chat', 'le_chat'), ('CIRTA', 'cirta')], max_length=100),
        ),
    ]
